basePath: /
definitions:
  request.CreatePostRequest:
    properties:
      created_user_id:
        type: integer
      description:
        maxLength: 200
        minLength: 1
        type: string
      status:
        type: integer
      title:
        maxLength: 200
        minLength: 1
        type: string
      updated_user_id:
        type: integer
    required:
    - description
    - title
    type: object
  request.CreateUserRequest:
    properties:
      address:
        type: string
      created_user_id:
        type: integer
      date_of_birth:
        type: string
      email:
        maxLength: 200
        minLength: 1
        type: string
      name:
        maxLength: 200
        minLength: 1
        type: string
      password:
        maxLength: 200
        minLength: 1
        type: string
      phone:
        type: string
      profile_photo:
        type: string
      type:
        default: "1"
        type: string
    required:
    - email
    - name
    - password
    type: object
  request.LoginRequest:
    properties:
      email:
        maxLength: 200
        minLength: 1
        type: string
      password:
        maxLength: 200
        minLength: 1
        type: string
    required:
    - email
    - password
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Bulletin Board Service API in Go using Gin Frameworl
  title: Bulletin Board API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticates user login
      parameters:
      - description: Login Request Body
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User Login
      tags:
      - LOGIN
  /api/posts:
    get:
      description: Returns post list
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get post list
      tags:
      - POST
    post:
      consumes:
      - application/json
      description: Creates a new post
      parameters:
      - description: Post Request Body
        in: body
        name: CreatePostRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a new post
      tags:
      - POST
  /api/posts/{id}:
    delete:
      description: Returns nil
      parameters:
      - description: Delete post by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete a post
      tags:
      - POST
    get:
      description: Returns Found post
      parameters:
      - description: Find post by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Find a post by id
      tags:
      - POST
    put:
      consumes:
      - application/json
      description: Update a post
      parameters:
      - description: Post Request Body
        in: body
        name: CreatePostRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreatePostRequest'
      - description: Update post by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Update a post
      tags:
      - POST
  /api/users:
    get:
      description: Returns user list
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get user list
      tags:
      - USER
    post:
      consumes:
      - application/json
      description: Creates a new user
      parameters:
      - description: User Request Body
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - USER
  /api/users/{id}:
    delete:
      description: Returns nil
      parameters:
      - description: Delete user by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete a user
      tags:
      - USER
    get:
      description: Returns Found user
      parameters:
      - description: Find user by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Find a user by id
      tags:
      - USER
    put:
      consumes:
      - application/json
      description: Update a user
      parameters:
      - description: User Request Body
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      - description: Update user by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Update a user
      tags:
      - USER
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
